### ISSUE TITLE
Missing v1 tag

### ISSUE THREAD

**Issue by jkroepke** [helmfile/helmfile-action#30]
The example from README.md

```
- uses: helmfile/helmfile-action@v1
```

fails with:

```
Unable to resolve action `helmfile/helmfile-action@v1`, unable to find version `v1`
```

Reason: There is no such release or tag for v1 on this repository.

Hint: I'm using a [workflow](https://github.com/jkroepke/setup-vals/blob/main/.github/workflows/update-major-tag.yaml) to update the floating tag. However, the Release for the tag needs to be created once.

**Comment by yxxhero** [comment]
Maybe v1.0.0

**Comment by jkroepke** [comment]
v1.0.0 is working fine. But I also recommend to setup a floating tag like v1

**Comment by yxxhero** [comment]
ok. I will try create v1 tag.
