### ISSUE TITLE
Support diff --detailed-exitcode

### ISSUE THREAD

**Issue by jkroepke** [helmfile/helmfile-action#31]
The running `helmfile diff --detailed-exitcode` expect exit code 2 on a success run.

From github actions point of view, it's not possible to allow specific exit code. If helm diff detect changes, it would exit with exit code 2 and helmfile, too. This would result into an action failure.

Proposed solution:

Catch the exit code 2 from helmfile and return exit code 0 to GitHub actions. The exit code should be stored into an output variable. 

Use-Case: Run the deploy step only if there is a diff.

**Comment by yxxhero** [comment]
@jkroepke PR is welcome. 
@bonddim did you have free time for the issue? thanks so much.

**Comment by bonddim** [comment]
You're very fast with this :)
I thought to add additional input to ignore exit code and not ignore it by default as was added by current PR...

**Comment by yxxhero** [comment]
@bonddim PR is welcome.

**Comment by yxxhero** [comment]
@bonddim would you have time to take a look at this isuee? thanks so much.

**Comment by bonddim** [comment]
@yxxhero, 
Yes, I'll do, but I have no time for this now.

**Comment by yxxhero** [comment]
@jkroepke ok. thanks for your feedback. it will release a new one when this issue is fixed.

**Comment by bonddim** [comment]
@yxxhero, @jkroepke is right. 
You may close this issue as resolved

**Comment by yxxhero** [comment]
@bonddim got it. closed.
